@extends('layouts.workspace')

@section('title', $form ? 'Editar formulario' : 'Crear formulario')
@section('eyebrow', 'Administración')
@section('heading', $form ? 'Editar formulario' : 'Crear formulario')

@section('page_styles')
    .intro{margin:-24px 0 25px}.back{display:inline-block;margin:-12px 0 20px;color:var(--brand);text-decoration:none;font-size:.9rem}label{display:block;margin:17px 0 6px;font-size:.87rem;font-weight:750}input,textarea,select{width:100%;padding:.78rem;border:1px solid #abb5c4;border-radius:8px;background:#fff;font:inherit}textarea{min-height:80px;resize:vertical}.fields{display:grid;gap:12px;margin-top:10px}.field{padding:16px;background:#f8f8ff;border:1px solid #e4e2ff;border-radius:11px}.field-grid{display:grid;grid-template-columns:1.3fr .8fr auto;gap:10px;align-items:end}.check{display:flex;gap:7px;align-items:center;margin:0 0 11px;font-size:.82rem}.check input{width:auto}.remove{margin-top:12px;padding:0;border:0;background:transparent;color:var(--danger);cursor:pointer;font:inherit;font-size:.82rem}.add{margin-top:14px;padding:.68rem .9rem;color:var(--brand);background:#f0efff;border:0;border-radius:8px;cursor:pointer;font:inherit;font-weight:750}.save{margin-top:24px;padding:.85rem 1.1rem;color:#fff;background:var(--brand);border:0;border-radius:9px;cursor:pointer;font:inherit;font-weight:800}.errors{margin:10px 0;padding:10px 14px;color:#9f1239;background:#fff1f2;border-radius:8px;font-size:.85rem}@media(max-width:620px){.field-grid{grid-template-columns:1fr}}
@endsection

@section('content')
    <a class="back" href="{{ route('forms.index') }}">← Formularios</a><p class="intro">Los datos básicos de cuenta ya existen; agrega o ajusta la información necesaria para la solicitud.</p>
    <form class="card" method="POST" action="{{ $form ? route('forms.update', $form) : route('forms.store') }}">@csrf @if ($form) @method('PUT') @endif @if ($errors->any())<div class="errors">Revisa los campos marcados e inténtalo de nuevo.</div>@endif<label for="name">Nombre del formulario</label><input id="name" name="name" value="{{ old('name', $form?->name) }}" placeholder="Solicitud de identidad" required><label for="description">Descripción para los miembros</label><textarea id="description" name="description" placeholder="Indica qué información deben proporcionar.">{{ old('description', $form?->description) }}</textarea><label>Campos adicionales</label><div id="fields" class="fields"></div><button class="add" id="add-field" type="button">+ Agregar campo</button><br><button class="save" type="submit">{{ $form ? 'Guardar cambios' : 'Crear formulario' }}</button></form>
    <template id="field-template"><section class="field"><div class="field-grid"><div><label>Etiqueta del campo<input data-name="label" placeholder="Ej. Tipo de vinculación laboral" required></label></div><div><label>Tipo<select data-name="type"><option value="text">Texto corto</option><option value="textarea">Texto largo</option><option value="select">Lista de opciones</option><option value="aplicativo">Aplicativo</option><option value="modulo">Módulo del aplicativo</option><option value="number">Número</option><option value="date">Fecha</option></select></label></div><label class="check"><input data-name="required" type="checkbox" value="1"> Obligatorio</label></div><label class="options">Opciones de la lista, separadas por comas<input data-name="options" placeholder="Empleado, Contratista, Practicante"></label><button class="remove" type="button">Eliminar campo</button></section></template>
    <script>const container=document.querySelector('#fields'),template=document.querySelector('#field-template');function renumber(){container.querySelectorAll('.field').forEach((field,index)=>field.querySelectorAll('[data-name]').forEach(input=>input.name=`fields[${index}][${input.dataset.name}]`))}function addField(values={}){const node=template.content.cloneNode(true),field=node.querySelector('.field'),type=field.querySelector('[data-name="type"]'),options=field.querySelector('.options');field.querySelector('.remove').addEventListener('click',()=>{field.remove();renumber()});field.querySelector('[data-name="label"]').value=values.label??'';type.value=values.type??'text';field.querySelector('[data-name="required"]').checked=Boolean(values.required);field.querySelector('[data-name="options"]').value=values.options??'';const toggleOptions=()=>options.hidden=type.value!=='select';type.addEventListener('change',toggleOptions);toggleOptions();container.append(node);renumber()}document.querySelector('#add-field').addEventListener('click',addField);const existingFields=@json($formFields);(existingFields.length?existingFields:[{}]).forEach(addField);</script>
@endsection
