<!doctype html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title', 'Espacio de trabajo') · SIGA</title>
    <style>
        :root{--ink:#182235;--muted:#667085;--line:#e5e9f1;--brand:#4b42ef;--canvas:#f5f7fb;--surface:#fff;--success:#0a9f6e;--danger:#a51d3c}*{box-sizing:border-box}body{margin:0;min-height:100vh;color:var(--ink);background:var(--canvas);font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}.shell{display:grid;grid-template-columns:248px minmax(0,1fr);min-height:100vh}.sidebar{display:flex;flex-direction:column;padding:26px 16px;color:#d8d7ff;background:#1c1a4a}.logo{display:flex;align-items:center;gap:11px;padding:0 10px 34px;color:#fff;font-size:1.2rem;font-weight:800}.mark,.avatar{display:grid;place-items:center;font-weight:800}.mark{width:34px;height:34px;color:var(--brand);background:#fff;border-radius:10px}.workspace-label{margin:10px;color:#9996d4;font-size:.69rem;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.nav-link{display:block;padding:11px 12px;margin-bottom:3px;color:#cfcef9;border-radius:10px;text-decoration:none;font-size:.93rem}.nav-link.active{color:#fff;background:var(--brand);font-weight:700}.sidebar-footer{margin-top:auto;padding:15px 10px 0;border-top:1px solid #363373;color:#aaa8df;font-size:.78rem}.logout{width:100%;margin-top:12px;padding:9px;color:#e6e5ff;background:transparent;border:1px solid #4c4990;border-radius:8px;cursor:pointer;font:inherit}.content{padding:30px clamp(20px,4vw,56px) 50px}.topbar{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:36px}.eyebrow{margin:0 0 5px;color:var(--brand);font-size:.74rem;font-weight:800;letter-spacing:.08em;text-transform:uppercase}h1{margin:0;font-size:clamp(1.65rem,3vw,2.25rem);letter-spacing:-.055em}.user{display:flex;align-items:center;gap:10px}.avatar{width:40px;height:40px;color:#fff;background:linear-gradient(135deg,#736cff,#3730c9);border-radius:50%}.user-name{font-size:.88rem;font-weight:750}.user-role{color:var(--muted);font-size:.76rem}.notice{padding:12px 15px;margin-bottom:20px;color:#176b4b;background:#edfbf5;border-radius:9px;font-size:.88rem}.card{padding:22px;background:var(--surface);border:1px solid var(--line);border-radius:15px}.primary{padding:.75rem 1rem;color:#fff;background:var(--brand);border:0;border-radius:8px;font:inherit;font-weight:750;cursor:pointer}.field{width:100%;padding:.75rem;margin:10px 0;border:1px solid #b9c2d0;border-radius:8px;background:#fff;font:inherit}.intro,.empty{color:var(--muted)}@media(max-width:800px){.shell{grid-template-columns:72px minmax(0,1fr)}.sidebar{width:72px;padding-inline:10px}.logo span:not(.mark),.workspace-label,.nav-link span,.sidebar-footer{display:none}.nav-link{text-align:center}.content{padding:25px 18px}}@media(max-width:560px){.shell{display:block}.sidebar{display:none}.content{padding:24px 16px}.user-name,.user-role{display:none}}
        @yield('page_styles')
    </style>
</head>
<body><div class="shell"><aside class="sidebar"><div class="logo"><span class="mark">S</span><span>SIGA</span></div><p class="workspace-label">Espacio de trabajo</p>@if (auth()->user()->is_organization_admin)<a class="nav-link @if(request()->routeIs('dashboard')) active @endif" href="{{ route('dashboard') }}">▦ <span>&nbsp; Resumen</span></a><a class="nav-link @if(request()->routeIs('applications.*')) active @endif" href="{{ route('applications.index') }}">▣ <span>&nbsp; Aplicativos y módulos</span></a><a class="nav-link @if(request()->routeIs('forms.*')) active @endif" href="{{ route('forms.index') }}">▤ <span>&nbsp; Formularios</span></a>@else<a class="nav-link @if(request()->routeIs('member.home')) active @endif" href="{{ route('member.home') }}">▦ <span>&nbsp; Mi cuenta</span></a><a class="nav-link @if(request()->routeIs('requests.*')) active @endif" href="{{ route('requests.index') }}">▤ <span>&nbsp; Solicitudes</span></a>@endif<div class="sidebar-footer">Sesión protegida<form method="POST" action="{{ route('logout') }}">@csrf<button class="logout" type="submit">Cerrar sesión</button></form></div></aside><main class="content"><header class="topbar"><div><p class="eyebrow">@yield('eyebrow', 'Espacio de trabajo')</p><h1>@yield('heading')</h1></div><div class="user"><div class="avatar">{{ str(auth()->user()->name)->substr(0, 1)->upper() }}</div><div><div class="user-name">{{ auth()->user()->name }}</div><div class="user-role">{{ auth()->user()->is_organization_admin ? 'Administrador' : 'Miembro' }}</div></div></div></header>@if (session('status'))<div class="notice">{{ session('status') }}</div>@endif @yield('content')</main></div></body>
</html>
